name: 'Auto merge pull requests from specific users'
description: 'Some PRs are opened by a bot bumping deps and these do not require manual review if the tests pass'
author: 'Tom Heyes'
inputs:
  autoMergeUser:
    description: 'input description here'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
