name: git-branch-strategy-action
description: Automates custom git branch strategy action.
author: Jeongseok Kang

branding:
  icon: git-pull-request
  color: green

# Define your inputs here.
inputs:
  github-token:
    description: GitHub personal access token with privilege.
    required: true
  main-branch:
    description: GitHub main branch.
    required: true
    type: choice
    options:
      - main
      - master  # legacy
  release-branch:
    description: GitHub branch to release. Allows a regex.
    default: null
  deploy-branch:
    description: Git branch to deploy service to cloud.
    default: null
  label:
    description: GitHub label for a pull request.
    default: gitflow
  # auto-merge:
  #   description: Automates pull request merge.
  #   type: boolean
  #   default: true
  # require-merge:
  #   description: Assert
  #   type: boolean
  #   default: false

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
