name: 'Daniel Genis'
description: 'GH actions plugin to poll an url until the expected response is present'
author: 'Gynzy BV'
inputs:
  url:
    required: true
    description: 'URL to poll. i.e.: https://example.com/test.txt'
  attempts:
    required: false
    description: 'how many retries should we do? i.e. 100'
    default: '500'
  interval:
    required: false
    description: 'how long should we wait between polls? in millieseconds'
    default: '1000'
  expectedContent:
    required: true
    description: 'the response content which we expect'
runs:
  using: 'node16'
  main: 'dist/index.js'
