name: "Require All Codeowners"
description: "Ensures all code owners have approved."
author: "John McCall"

branding:
  icon: "user-check"
  color: "green"

inputs:
  pr-number:
    description: "The number of the pull request."
    required: true
    default: ${{ github.event.number }}
  repo-token:
    description: "Github token for authentication."
    required: false
    default: ${{ github.token }}
  repository:
    description: "owner/repository of pull request."
    required: false
    default: ${{ github.repository }}

outputs:
  approved:
    description: "Code owners who have approved the pull request."
  approved-count:
    description: "Number of approved code owners."
  pending:
    description: "Code owners who have not approved the pull request."
  pending-count:
    description: "Number of pending code owners."

runs:
  using: node20
  main: dist/index.js
