name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
on:
  workflow_dispatch:
   inputs:
     organization: # change this
       required: false
       description: 'org'
       default: 'self_hkr'
    
     workspace: # change this
       required: false
       description: 'workspace'
       default: 'learn-terraform-github-actions'

     apiToken:
       required: false
       description: 'token'
       default: ${{ secrets.API_TOKEN }}
     
runs:
  using: 'node16'
  main: 'dist/index.js'

